source 'http://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'activerecord', '~> 5.1', '>= 5.1.5'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.13'
gem 'rake'
gem 'require_all'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'pg'
gem 'bcrypt'
gem 'tux'
gem 'sinatra-flash'
