source 'http://rubygems.org'

gem 'sinatra', '~> 2.2'
gem 'activerecord', '~> 5.1', '>= 5.1.5'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.13'
gem 'rake'
gem 'require_all'
gem 'thin'
gem 'pg'
gem 'bcrypt'
gem 'sinatra-flash'

gem 'shotgun'
gem 'pry'
gem 'tux'

gem 'rspec'
gem 'capybara'
gem 'rack-test'
gem 'database_cleaner'
gem 'launchy'
