development:
  adapter: postgresql
  encoding: unicode
  database: supply_inventory
  pool: 2
  username: supply_inventory
  password: inventorydb

test:
  adapter: postgresql
  encoding: unicode
  database: supply_inventory_testdb
  pool: 2
  username: supply_inventory
  password: inventorydb

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
